declare module 'cornerstone-core'
declare module 'cornerstone-tools'
declare module 'cornerstone-wado-image-loader'
declare module 'cornerstone-math'
declare module 'hammerjs'
declare module '@cornerstonejs/dicom-image-loader'
